site_name: pipeline_documentation
site_url: https://github.com/ramsainanduri/pipeline_documentation.git

theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
    - 'Pipeline Information': 'index.md'
    - Introduction: 'introduction.md'
    - 'Minimum Requirements': 'scope.md'
    - Usage: 'usage.md'
    - Profiles: 'profiles.md'
    - Workflow: 'workflow.md'